version: 2
jobs:

  build:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/tax
    steps:
      - checkout
      - run:
          name: Run tests
          command: cargo test
      - run:
          name: Build
          command: cargo build --release
